# Generated by Django 5.1.4 on 2025-05-09 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('text', models.TextField(help_text="Bu kiritilgan ma'lumotni AI o'rganib oladi!", verbose_name="AI o'rganish matni")),
                ('status', models.BooleanField(default=True, help_text="Matnni o'rganish yoki o'rganmaslik holati.", verbose_name='Holati')),
            ],
            options={
                'verbose_name': "Ma'lumot ",
                'verbose_name_plural': "Ma'lumotlar ",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xabar ',
                'verbose_name_plural': 'Xabarlar ',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['author', 'created_at'], name='Control_mes_author__bf6ad6_idx')],
            },
        ),
    ]
